# Generated by Django 3.1.14 on 2025-05-29 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leave_city', models.CharField(max_length=100, null=True)),
                ('arrive_city', models.CharField(max_length=100, null=True)),
                ('leave_airport', models.CharField(max_length=100, null=True)),
                ('arrive_airport', models.CharField(max_length=100, null=True)),
                ('leave_time', models.DateTimeField(null=True)),
                ('arrive_time', models.DateTimeField(null=True)),
                ('capacity', models.IntegerField(default=0, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('book_sum', models.IntegerField(default=0, null=True)),
                ('income', models.FloatField(default=0, null=True)),
                ('seat_type', models.CharField(choices=[('头等舱', '头等舱'), ('公务舱', '公务舱'), ('经济舱', '经济舱')], default='经济舱', max_length=100)),
                ('user', models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pay_time', models.DateTimeField(null=True)),
                ('fetch_time', models.DateTimeField(null=True)),
                ('refund_time', models.DateTimeField(null=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('is_fetch', models.BooleanField(default=False)),
                ('is_refund', models.BooleanField(default=False)),
                ('can_modify', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksystem.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
